services:
  gig-backend:
    build: .
    image: gig-backend:latest
    container_name: gig-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    # make sure your app uses this URI or set it in .env
    environment:
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017/yourdb}
    volumes:
      - .misc/logger:/app/logger/
    networks:
      - backend_net

networks:
  backend_net:
    external: true   # use the same network created by the DB stack
    name: backend_net
