version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-database
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .misc/lib/postgresql/data:/var/lib/postgresql/data
      - .misc/keycloak/import/psql/keycloak:/docker-entrypoint-initdb.d
    networks:
      - backend_net
    user: "0:0"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - .misc/keycloak/import/realm:/opt/keycloak/data/import
    ports:
      - "127.0.0.1:3000:8080"  # bind to localhost only
    networks:
      - backend_net
    command: >
      start
      --features=scripts,preview
      --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: "auth.giggle.global"
      KC_PROXY: "edge"
    user: "0:0"

networks:
  backend_net:
    name: backend_net
