version: "3.8"

services:
  mongo-db:
    image: mongo
    container_name: mongodb
    volumes:
      - ./lib/mongodb:/data/db
      - ./lib/mongodb/logs:/var/log/mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - backend_net
    restart: unless-stopped
    user: "0:0"

networks:
  backend_net:
    name: backend_net
