version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres-database
    env_file:
      - .env      # Use a local .env file for simplicity
    restart: unless-stopped
    volumes:
      - ./lib/postgresql/data:/var/lib/postgresql/data
      - ./keycloak/import/psql:/lib/postgresql/data
      - ./keycloak/import/psql/keycloak:/docker-entrypoint-initdb.d
    networks:
      - keycloak_net
    user: "0:0"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    env_file:
      - .env      # Use the same .env file for both services
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./keycloak/import/realm:/opt/keycloak/data/import
    user: "0:0"
    ports:
      - "3000:8080"
    networks:
      - keycloak_net
    command: >
      start-dev
      --features=scripts,preview
      --import-realm

networks:
  keycloak_net:
    name: keycloak_net
