# app/repositories/token.py
import secrets
import string
import uuid
from datetime import datetime, timezone, timedelta
from typing import Optional, List
from pymongo.collection import Collection
from fastapi import HTTPException
from app.core.db import database
from app.models.token import SignupTokenCreate, SignupTokenBase, SignupTokenOut

class TokenRepository:
    def __init__(self):
        self.collection: Collection = database["signup_tokens"]
        # ensure indexes (call once at init)
        try:
            self.collection.create_index("token", unique=True)
            self.collection.create_index("generated_by")
            self.collection.create_index("expires_at", expireAfterSeconds=0)  # optional TTL removal
        except Exception:
            pass

    def _now(self):
        return datetime.now(timezone.utc)
    
    def _generate_signup_code(self, length: int = 9) -> str:
        alphabet = string.ascii_uppercase + string.digits  # A-Z + 0-9
        return ''.join(secrets.choice(alphabet) for _ in range(length))

    def create_token(self, payload: SignupTokenCreate) -> SignupTokenOut:
        now = self._now()
        expires_at = now + timedelta(seconds=payload.ttl_seconds)
        # token = secrets.token_urlsafe(16)  # safe random token
        token = self._generate_signup_code(9)
        doc = {
            "token": token,
            "generated_by": payload.generated_by,
            "target_role": payload.target_role.value,
            "created_at": now,
            "expires_at": expires_at,
            "used": False,
            "used_by": None,
            "used_at": None,
        }
        try:
            self.collection.insert_one(doc)
        except Exception as exc:
            raise HTTPException(500, "Failed to create token") from exc
        return SignupTokenOut(**doc)

    def count_active_tokens_by_user(self, user_id: str) -> int:
        now = self._now()
        # count tokens generated by user that are not expired (expires_at > now)
        return self.collection.count_documents({"generated_by": user_id, "expires_at": {"$gt": now}})

    def get_by_token(self, token: str) -> Optional[dict]:
        return self.collection.find_one({"token": token}, {"_id": 0})

    def mark_used(self, token: str, used_by_user_id: str) -> dict:
        now = self._now()
        # update only if token exists, not used and not expired
        res = self.collection.find_one_and_update(
            {"token": token, "used": False, "expires_at": {"$gt": now}},
            {"$set": {"used": True, "used_by": used_by_user_id, "used_at": now}},
            projection={"_id": 0},
            return_document=True
        )
        if not res:
            raise HTTPException(400, "Token is invalid, expired or already used")
        return res

    def list_tokens_for_user(self, user_id: str) -> List[dict]:
        return list(self.collection.find({"generated_by": user_id}, {"_id": 0}).sort("created_at", -1))
    
    def get_active_token_for_user(self, user_id: str) -> Optional[dict]:
        """Get the active (non-expired, unused) token for a user"""
        now = self._now()
        token = self.collection.find_one(
            {"generated_by": user_id, "used": False, "expires_at": {"$gt": now}},
            {"_id": 0}
        )
        return token

    def revoke_token(self, token: str) -> dict:
        res = self.collection.find_one_and_update(
            {"token": token},
            {"$set": {"expires_at": self._now(), "used": True}},
            projection={"_id": 0},
            return_document=True
        )
        if not res:
            raise HTTPException(404, "Token not found")
        return res
